mp_clean_core:
    resource: "@MPCleanCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

mpclean_home:
    path:   /index
    defaults: {_controller: MPCleanCoreBundle:Main:index}