mp_clean_index:
    path:     /accueil
    defaults: { _controller: MPCleanCoreBundle:Main:index }

mp_clean_contact:
    path:     /contact
    defaults: {_controller: MPCleanCoreBundle:Main:contact}